#!/bin/bash
#
# syslog-ng     This starts and stops syslog-ng
#
# chkconfig:    2345 12 88
# description:  syslog-ng is an alternative system logger
# processname:  syslog-ng
# pidfile:      /var/run/syslog-ng.pid
### BEGIN INIT INFO
# Provides: $syslog-ng
### END INIT INFO

# *****
# This file is managed by chef
# Local changes will be overwritten
# *****

# Source function library.
if [ -x /etc/init.d/functions ]; then
  . /etc/init.d/functions
else
  . /lib/lsb/init-functions
fi

binary="/sbin/syslog-ng"
if [ ! -x "${binary}" ]; then
  binary="/usr/sbin/syslog-ng"
fi

if [ -d /var/lock/subsys ]; then
  lockfile=/var/lock/subsys/syslog-ng
else
  lockfile=/var/lib/syslog-ng/syslog-ng.pid
fi

echo 'binary:' "${binary}"
echo 'lockfile:' "${lockfile}"
echo 'Command:' "${1}"

if [ ! -x "${binary}" ]; then
  echo 'Cannot find syslog-ng in' "${binary}"
  exit 0
fi

RETVAL=0

start() {
  echo -n "Starting syslog-ng: "
  cat /etc/syslog-ng/conf.d/* > /etc/syslog-ng/syslog-ng.conf
  daemon $binary
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch "${lockfile}"
}

stop() {
  echo -n "Shutting down syslog-ng: "
  killproc syslog-ng
  RETVAL=$?
  echo
  if [ $RETVAL -eq 0 ]; then
    rm -f "${lockfile}"
    [ -f /var/run/syslog-ng.pid ] && rm -f /var/run/syslog-ng.pid
  fi
}

restart() {
  echo -n "Restarting syslog-ng: "
  cat /etc/syslog-ng/conf.d/* > /etc/syslog-ng/syslog-ng.conf
  $binary --syntax-only
  RETVAL=$?
  echo
  if [ $RETVAL -eq 0 ]; then
    stop
    sleep 2
    start
  fi
}

reload() {
  echo -n "Reloading syslog-ng: "
  cat /etc/syslog-ng/conf.d/* > /etc/syslog-ng/syslog-ng.conf
  $binary --syntax-only
  RETVAL=$?
  if [ $RETVAL -eq 0 ]; then
    killproc syslog-ng -1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status syslog-ng
    ;;
  restart)
    restart
    ;;
  reload)
    reload
    ;;
  condrestart)
    [ -f "${lockfile}" ] && restart
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|condrestart}"
    ;;
esac