# Generated by Chef for <%= node[:fqdn] %>
# Local modifications will be overwritten.
#
# <%= node[:syslog_ng][:config_dir] %>/conf.d/<%= [@application[:index], @application[:name]].join %>
#


source s_udp_<%= @application[:name] %> {
  udp (ip(<%= @application[:host] %>) port(<%= @application[:port] %>));
};

destination d_file_<%= @application[:name] %> {
  file("<%= @application[:log_base] %>/<%= @application[:name] %>/<%= @application[:log_name]%>");
};

log {
  source(s_udp_<%= @application[:name] %>);
  destination(d_file_<%= @application[:name] %>);
};

# do not forget the empty line
